line1=Opcje konfiguracyjne,11
dont_convert=Lista u¿ytkowników Uniksa nie dodawanych do listy hase³ Samby,0
sort_mode=Porz±dkowaæ u¿ytkowników i&nbsp;grupy wg nazw,1,1-Tak,0-Nie
line2=Konfiguracja systemu,11
smb_conf=Lokalizacja pliku konfiguracyjnego Samby,0
smb_passwd=Lokalizacja pliku hase³ Samby,3
samba_status_program=Pe³na ¶cie¿ka do <tt>smbstatus</tt>,0
samba_password_program=Pe³na ¶cie¿ka do <tt>smbpasswd</tt>,0
samba_server=Pe³na ¶cie¿ka do <tt>smbd</tt>,0
name_server=Pe³na ¶cie¿ka do <tt>nmbd</tt>,0
winbind_server=Pe³na ¶cie¿ka do <tt>winbindd</tt>,0
swat_path=Pe³na ¶cie¿ka do <tt>swat</tt>,3,Brak
smbgroupedit=Pe³na ¶cie¿ka do <tt>smbgroupedit</tt>,3,Brak
pdbedit=Pe³na ¶cie¿ka do <tt>pdbedit</tt>,3,Brak
net=Pe³na ¶cie¿ka do polecenia <tt>net</tt>,3,Brak
start_cmd=Polecenie uruchamiaj±ce serwery Samby,3,Brak
stop_cmd=Polecenie zatrzymuj±ce serwery Samby,3,Brak
restart_cmd=Polecenie restartu serwerów Samba,3,Tylko zatrzymaj i uruchom
start_cmd_wb=Polecenie do uruchomienia serwerów Winbind,0
stop_cmd_wb=Polecenie do zatrzymania serwerów Winbind,0
