line1=Nastavení konfigurace,11
mail_dir_qmail=Qmail mail adresář v domovském adresáři,0
start_cmd=Příkaz spouštějící QMail,3,Právě běžet jako skript
mail_file=Mail soubor Sendmailu v domovském adresáři,0
line2=Konfigurace systému,11
mail_style=Styl adresáře s mail soubory,4,0-mail/username,1-mail/u/username,2-mail/u/us/username,3-mail/u/s/username
stop_cmd=Příkaz ukončující QMail,3,Právě zabít qmail-send
sort_mode=Třídit tabulky podle,1,0-Pořadí v souboru,1-Názvu
mail_dir=Umístění mail souboru Sendmailu,3,Soubor pod domovským adresářem
perpage=Mail zprávy zobrazitelné na jednu stránku,0,6
mail_system=Formát mailboxu,1,0-Jeden soubor,1-Adresář
max_records=Maximální počet zobrazených záznamů v tabulkách,0,6
qmail_dir=QMail základní adresář,0
send_mode=Poslat mail přes připojení k,3,qmail-inject spouštěč
