line1=Možnosti konfigurace,11
smrsh_program_dir=Adresář obsahující bezpečnostní programy uložení Sendmailu,3,Kdekoliv
perms=Práva pro soubory majordomu,1,1-zapisovatelné uživateli,0-zapisovatelné uživateli a skupinami
line2=Konfigurace systému,11
program_dir=Adresář obsahující majordomo programy,0
majordomo_cf=Úplůná cesta ke konfiguračnímu souboru majordomu,0
sort_mode=Třídit mailové seznamy podle,1,1-názvu,0-pořadí vytvoření
aliases_file=Soubor aliasů Sendmail-stylu,10,postfix-Get from Postfix,-Get from Sendmail,Other file
wrapper_path=Cesta k majordomo wrapper,3,V adresáři programů
dynamic=Použít náhodná čísla pro seznam aliasů?,1,1-ano,0-ne
