line2=Konfiguracja serwera,11
cfengine_dir=Ścieżka do plików i katalogów,0
cfengine=Ścieżka do programu cfengine,0
cfengine_conf=Ścieżka do pliku cfengine.conf,3,Automatycznie
cfrun=Ścieżka do programu cfrun,0
cfrun_hosts=Ścieżka do pliku opcji serwera ,3,Automatycznie
cfd=Ścieżka do programu cfd,0
cfd_conf=Ścieżka do pliku cfd.conf,3,Automatycznie
start_cmd=Ścieżka do uruchomienia cfd,3,Uruchom tylko daemona
stop_cmd=Ścieżka do zatrzymania cfd,3,Tylko ubij proces
