cfengine_dir=Trayectoria a directorio de archivos de configuración,0
cfengine=Trayectoria a programa cfengine,0
cfengine_conf=Trayectoria a archivo cfengine.conf,3,Automática
cfrun=Trayectoria a programa cfrun,0
cfrun_hosts=Trayectoria a archivo de opciones de servidor,3,Automática
cfd=Trayectoria a programa cfd,0
cfd_conf=Trayectoria a archivo cfd.conf,3,Automática
start_cmd=Comando para arrancar cfd,3,Sólo ejecutar daemon
stop_cmd=Comando para parar cfd,3,Sólo matar proceso
