line2=Konfigurace systému,11
plib=Cesta ke sdíleným knihovnám PostgreSQL,3,Není potřeba
stop_cmd=Příkaz k ukončení PostgreSQL,3,Zabít proces
hba_conf=Cesta ke konfiguračnímu souboru s přístupy hostů,0
nodbi=Použít DBI pro připojení je-li k dispozici?,1,0-Yes,1-No
line1=Nastavení konfigurace,11
login=Přihlašovací jméno administrátora,0
pass=Heslo administrátora,12
start_cmd=Přikaz ke spuštění PostgreSQL,0
host=PostgreSQL host ke kterému se připojuje,3,localhost
basedb=Počáteční PostgreSQL databáze,0
perpage=Počet řádků zobrazujících se na jedné straně,0
setup_cmd=Příkaz k inicializaci PostgreSQL,3,Nic
pid_file=Cesta k PID souboru postmastera,0
psql=Cesta k příkazu psql,0
