#!/bin/bash

VERSION="$1"
PROD="$2"

if [ -z "$VERSION" ] ; then
    echo "Version not provided to $0: Unable to proceed." >&2
    exit 1
fi
# Make a running instance
docker run -it webminpkg /bin/true

# Find latest (the one we just made)
latest=$(docker ps -l -f ancestor=webminpkg --format "{{.ID}}")

preface="dev_"
if $PROD ; then
    preface=""
fi

echo "Copying from $latest (version=$VERSION, prod=$PROD)"
docker cp $latest:/webmin/deb/webmin_${VERSION}_all.deb ./${preface}rootsecure_webmin_${VERSION}.deb
docker rm $latest
