after_apply_cmd=Arahan untuk dijalankan selepas menerapkan konfigurasi,3,Tiada
macros=Direktori fail makro,0
config_dir=Direktori konfigurasi Shorewall6,0
display_zone_descriptions=Memaparkan penerangan zon dalam fail peraturan?,1,0-Tidak,1-Ya
actions=Fail tindakan Standard,9,40,5,\t
before_apply_cmd=Arahan untuk dijalankan sebelum menerap konfigurasi,3,Tiada
shorewall6=Lokasi kepada arahan shorewall6,0
