.TH ajaxterm "1" "May 2006" "ajaxterm 0.5" "User commands"
.SH NAME
ajaxterm \- Web based terminal written in python

.SH DESCRITPION
\fBajaxterm\fR is a web based terminal written in python and some AJAX
javascript for client side.
It can use almost any web browser and even works through firewalls.

.SH USAGE
\fBajaxterm.py\fR [options]

.SH OPTIONS
A summary of the options supported by \fBajaxterm\fR is included below.
    \fB-h, --help\fR            show this help message and exit
    \fB-pPORT, --port=PORT\fR   Set the TCP port (default: 8022)
    \fB-cCMD, --command=CMD\fR  set the command (default: /bin/login or ssh localhost)
    \fB-l, --log\fR             log requests to stderr (default: quiet mode)

.SH AUTHOR
Antony Lesuisse <al@udev.org>

This manual page was written for the Debian system by
Julien Valroff <julien@kirya.net> (but may be used by others).

.SH "REPORTING BUGS"
Report any bugs to the author: Antony Lesuisse <al@udev.org>

.SH COPYRIGHT
Copyright Antony Lesuisse <al@udev.org>

.SH SEE ALSO
- \fBajaxterm\fR wiki page: http://antony.lesuisse.org/qweb/trac/wiki/AjaxTerm
.br
- \fBajaxterm\fR forum: http://antony.lesuisse.org/qweb/forum/viewforum.php?id=2
