line0=Opcje konfigurowalne,11
wait=Domyślny tryb oczekiwania na kopię zapasową,1,1-Czekaj na zakończenie,0-Uruchom w tle
apply=Automatycznie stosować konfigurację menedżera?,1,1-Tak,0-Nie
groupmode=Pobierać informacje o grupie węzłów z,1,webmin-Modułu Indeksu Serwerów Webmina,oc-Menedżera bazy danych OCM,-Nikąd
showdirs=Zawsze wyświetlać zdalnych menedżerów?,1,1-Tak,0-Nie
line1=Ustawienia bazy danych Bacula,11
driver=Typ bazy danych,1,Pg-PostgreSQL,mysql-MySQL,SQLite-SQLite
user=Użytkownik do zalogowania w bazie danych,0
pass=Hasło do zalogowania,0
host=Serwer bazy danych Bacula,3,Ten system
db=Baza danych lub plik zawierający informację Bacula,0
line2=Ustawienia pliku,11
bacula_dir=Katalog konfiguracyjny Bacula,0
bextract=Pełna ścieżka do komendy <tt>bextract</tt>,0
bls=Pełna ścieżka do komendy <tt>bls</tt>,0
btape=Pełna ścieżka do komendy <tt>btape</tt>,0
init_start=Uruchom i zatrzymaj Bacula używając,1,1-Skryptów Init,0-polecenia <tt>bacula</tt>
