host=Hostnaam om mee te verbinden,3,Automatisch
port=Poort om mee te verbinden,3,Standaard
proxy=Gebruik een proxy om te verbinden met een andere hosts?,1,1-Ja,0-Nee
mode=Verbindings type,1,0-Telnet,1-Beveiligde Shell (aanbevolen)
sizemode=Applet grote,1,0-80x24 karakters (in standaard letter) ,1-Maximum,2-Custom grote
size=Custom breedte x hoogte,0
fontsize=Letter grote in punten,3,Standaard
detach=Aparte window mode,1,1-Ja,0-Nee
no_test=Test de telnet of SSH server?,1,0-Ja,1-Nee
