rpc_inetd=Inetd podporuje RPC programy,1,1-ano,0-ne
deny_file=Úplná cesta k souboru, zamezující přístup k tcpd,3
line1=Možnosti konfigurace,11
qm_mode=Podporuje neexistující programy serveru,1,1-ano,0-ne
sort_mode=Setřídit služby a programy podle,1,0-pořadí v souboru,1-jména,2-příznaků
protocols_file=Soubor síťových protokolů,0
line2=Konfigurace systému,11
tcpd_path=Úplná cesta k tcpd,3
extended_inetd=Rozšířená podpora inetd,1,0-původní,1-základní,2-rozšířená
ipv6=Podporuje IPv6 služby,1,1-ano,0-ne
inetd_conf_file=Konfigurační soubor inetd,0
allow_file=Úplná cesta k souboru, povolující přístup k tcpd,3
rpc_protocols=RPC podprotokoly,0
rpc_file=Soubor RPC služeb,0
restart_command=Příkaz, který restartuje inetd,0
services_file=Soubor síťových služeb,0
inetd_dir=Konfigurační adresář inetd,3,None
