stop_cmd=Příkaz k zastavení BIND,3,Ukončující proces
max_zones=Maximální počet zobrazených zón,0
named_group=Skupina, která spustí BIND bude jako,3,výchozí
reversezonefilename_format=Formát názvu reverse (reversního) souboru zóny,0
extra_forward=Extra typy záznamů pro forward zóny,0
show_list=Zobrazit domény jako,1,0-Ikony,1-Seznam
support_aaaa=Podporuje DNS adresy IPv6?,1,1-ano,0-ne
rev_def=Aktualizace reverse je,1,0-standardně zapnuta,1-standardně vypnuta,2-standardně se přepisuje
whois_cmd=Úplná cesto pro whois příkaz,0
line2=Možnosti souboru se zónami,11
line3=Konfigurace systému,11
updserial_on=Automaticky aktualizovat serial numbers?,1,1-ano,0-ne
zones_file=Přidat nové zóny do souboru,3,named.conf
file_perms=Přístupová práva pro soubory zóny (octal),3,výchozí
this_ip=Výchozí IP master (hlavního) serveru pro vzdálené slave zóny,3,IP adresa nebo hostname
soa_style=Styl Serial number,1,0-běžící číslo,1-založeno na datumu (YYYYMMDDnn)
ipv6_mode=Doména pro reverzní IPv6 adresy,1,1-ip6.arpa,0-ip6.int
rndcconf_cmd=Úplná cesta k příkazu rndc-confgen,0
records_order=Seřadit zobrazené záznamy podle,1,1-jména,2-hodnoty,3-IP,0-přidání
chroot=Změnit (root) adresář pro běh BINDu na,3,výchozí
largezones=Zobrazit záznamy v zónách?,1,0-Ano,1-Ne (pro rozsáhlé zóny)
short_names=Konvertovat jména v záznamech do kanonické podoby?,1,0-ano,1-ne
start_cmd=Příkaz, který spustí BIND,3,standardní
ndc_cmd=Příkaz pro přepsání zóny,0
no_pid_chroot=PID soubor je v chroot adresáři?,1,0-Ano,1-Ne
master_ttl=Přidat $ttl na začátek nového souboru se zónami?,1,1-ano,0-ne
named_conf=Plná cesta k souboru named.conf,0
line1=Možnosti zobrazení,11
file_owner=Vlastník souborů zóny (user:group),3,výchozí
no_chroot=Je named.conf v chroot adresáři?,1,0-Ano,1-Ne
relative_paths=Použít cestu k souboru soubor relativní zóny v <tt>named.conf</tt>?,1,1-Ano,0-Ne
by_view=Kategorizovat při zobrazení zóny?,1,1-ano,0-ne
slave_dir=Adresář pro slave (podřízený) soubor zóny,3,výchozí
default_prins=Výchozí master (hlavní) server pro hlavní zóny,0,Systémový hostname
allow_underscore=Povolit podtržení i jmen záznamů?,1,1-Ano,0-Ne
auto_chroot=Příkaz pro nalezení chroot adresáře,3,Použít výše uvedený pevný adresář
restart_cmd=Příkaz aplikující konfiguraci BIND,3,Posílající HUP signál
allow_wild=Jsou povoleny zástupné znaky?,1,1-ano,0-ne
line0=Cesty BIND,11
forwardzonefilename_format=Formát názvu forward (přesměrovaného) souboru zóny,0
master_dir=Adresář pro master (hlavní) soubor zóny,3,výchozí
default_master=Výchozí master (hlavní) server(y) pro slave (podřízené) zóny,0
rndc_conf=Úplná cesta k souboru rndc.conf,0
rndc_cmd=Úplná cesta k příkazu rndc,0
rev_must=Musí existovat reversní zóna?,1,1-ano,0-ne
allow_comments=Jsou povoleny komentáře u záznamů?,1,1-ano,0-ne
named_user=Uživatel, který spustí BIND bude jako,3,výchozí
soa_start=Počáteční číslo v date-based SOA,0,3
extra_reverse=Extra typy záznamů pro reverzní zóny,0
confirm_rec=Potvrdit před smazáním záznamů?,1,1-Ano,0-Ne
pid_file=Výchozí jméno PID souboru,3,/var/run/named.pid
confirm_zone=Potvrdit před smazáním zón?,1,1-Ano,0-Ne
free_nets=IP sítě pro volné adresy,3,Automatické
named_path=Plná cesta ke spustitelnému souboru named,0
