named_conf=Pe³na ¶cie¿ka do pliku named.conf,0
named_path=Pe³na ¶cie¿ka do programu named,0
whois_cmd=Pe³na ¶cie¿ka do polecenia whois,0
pid_file=Domy¶lna lokalizacja pliku z&nbsp;numerem PID,3,/var/run/named.pid
show_list=Wy¶wietlaj domeny jako,1,0-Ikony,1-Listê
soa_style=Postaæ numeru seryjnego,1,0-Numer kolejny,1-Oparty na dacie (RRRRMMDDnn)
records_order=Kolejno¶æ wy¶wietlania rekordów,1,1-Wg nazwy,2-Wg warto¶ci,3-Wg IP,0-W&nbsp;kolejno¶ci dodawania
chroot=Katalog chroot dla BINDa,3,Domy¶lny
start_cmd=Polecenie uruchamiaj±ce BINDa,3,Domy¶lne
max_zones=Maksymalna liczba wy¶wietlanych stref,0
rev_def=Aktualizacja DNS odwrotnego jest,1,0-Domy¶lnie w³±czona,1-Domy¶lnie wy³±czona
master_ttl=Dodawaæ $ttl na pocz±tku nowych plików stref,1,1-Tak,0-Nie
named_user=BIND jest uruchamiany jako u¿ytkownik,3,Domy¶lny
named_group=BIND jest uruchamiany jako grupa,3,Domy¶lna
master_dir=Katalog plików stref podstawowych,3,Domy¶lny
slave_dir=Katalog plików stref zapasowych/wykarczowanych,3,Domy¶lny
file_owner=W³a¶ciciel plików stref (u¿ytkownik:grupa),3,Domy¶lny
file_perms=Uprawnienia dla plików stref (ósemkowo),3,Domy¶lne
support_aaaa=W³±czyæ obs³ugê DNS dla adresów IPv6,1,0-Nie,1-Tak
allow_comments=Komentarze dla rekordów,1,0-Nie,1-Tak
allow_wild=Zezwoliæ na wieloznaczne (nie zalecane),1,0-Nie,1-Tak
allow_long=Zezwoliæ na d³ugie nazwy hostów,1,0-Nie,1-Tak
zones_file=Dodawaæ nowe strefy do pliku,3,named.conf
