line0=¦cie¿ki BINDa,11
chroot=Katalog chroot dla BINDa,3,Domy¶lny
no_chroot=Czy named.conf znajduje siê w katalogu chroot?,1,0-Tak,1-Nie
auto_chroot=Komenda do wyszukania katalogu chroot,3,U¿yj powy¿szego katalogu
named_user=BIND jest uruchamiany jako u¿ytkownik,3,Domy¶lny
named_group=BIND jest uruchamiany jako grupa,3,Domy¶lna
zones_file=Dodawaæ nowe strefy do pliku,3,named.conf
relative_paths=U¿yæ ¶cie¿ek pliku strefy wzglêdnej w <tt>named.conf</tt>?,1,1-Tak,0-Nie
keys_dir=Katalog dla kluczy DNSSEC,3,Taki sam jak pliki strefy
line1=Wy¶wietl opcje,11
show_list=Wy¶wietlaj domeny jako,1,0-Ikony,1-Listê
by_view=Kategoryzowaæ strefy wed³ug widoku?,1,1-Tak,0-Nie
records_order=Kolejno¶æ wy¶wietlania rekordów,1,1-Wg nazwy,2-Wg warto¶ci,3-Wg IP,0-W&nbsp;kolejno¶ci dodawania
max_zones=Maksymalna liczba wy¶wietlanych stref,0
rev_def=Aktualizacja DNS odwrotnego jest,1,0-Domy¶lnie w³±czona,1-Domy¶lnie wy³±czona
rev_must=Strefa odwrotna musi istnieæ?,1,1-Tak,0-Nie
support_aaaa=W³±czyæ obs³ugê DNS dla adresów IPv6,1,0-Nie,1-Tak
allow_comments=Zezwól na komentarze dla rekordów,1,0-Nie,1-Tak
allow_wild=Zezwoliæ na wieloznaczne,1,0-Nie,1-Tak
allow_underscore=Zezwoliæ na podkre¶lenia w nazwach rekordów?,1,1-Tak,0-Nie
short_names=Konwertowaæ nazwy rekordów do formy kanonicznej,1,0-Tak,1-Nie
extra_forward=Dodatkowe rodzaje rekordu dla stref prostych,0
extra_reverse=Dodatkowe rodzaje rekordu dla stref odwrotnych,0
largezones=Wy¶wietlaæ rekordy w strefach?,1,0-Tak,1-Nie (dla du¿ych stref)
default_view=Domy¶lny widok dla nowych stref,3,Pierwszy na li¶cie
line2=Opcje pliku strefy,11
soa_style=Postaæ numeru seryjnego,1,0-Numer kolejny,1-Oparty na dacie (RRRRMMDDnn),2-Czas unixowy
soa_start=Numer startowy w SOA bazuj±cym na dacie,0,3
master_ttl=Dodawaæ $ttl na pocz±tku nowych plików stref,1,1-Tak,0-Nie
master_dir=Katalog plików stref podstawowych,3,Domy¶lny
slave_dir=Katalog plików stref zapasowych/wykarczowanych,3,Domy¶lny
forwardzonefilename_format=Format nazwy plików strefy prostej,0
reversezonefilename_format=Format dla nazwy pliku strefy odwrotnej,0
file_owner=W³a¶ciciel plików stref (u¿ytkownik:grupa),3,Domy¶lny
file_perms=Uprawnienia dla plików stref (ósemkowo),3,Domy¶lne
default_prins=Domy¶lny serwer g³ówny dla stref g³ównych,3,Nazwa hosta systemu
default_master=Domy¶lny serwer(y) dla stref zapasowych,0
updserial_on=Automatycznie uaktualniaæ numery seryjne,1,1-Tak,0-Nie
ipv6_mode=Domena dla adresów odwrotnych IPv6,1,1-iop6.arpa,0-ip6.int
confirm_zone=Potwierdzaæ usuwanie stref?,1,1-Tak,0-Nie
confirm_rec=Potwierdzaæ usuwanie rekordów?,1,1-Tak,0-Nie
free_nets=Sieci IP dla wolnych adresów,3,Automatycznie
force_random=¬ród³o Entropy dla kluczy DNSSEC,1,1-/dev/random (bezpieczne, ale wolne),0-/dev/urandom (Prawdopodobnie niebezpieczne, ale szybkie)
spf_record=Prawdziwy typ rekordu dla Sender Permitted From,1,1-SPF,0-TXT
line2.5=Klaster serwerów zapasowych,11
this_ip=IP domy¶lnego serwera g³ównego dla zdalnych stref zapasowych,3,Adres IP nazwy hosta
other_slaves=Dodaæ inne adresy IP serwerów zapasowych do listy serwerów g³ównych na serwerach zapasowych?,1,1-Tak,0-Nie
extra_slaves=Dodatkowe adresy IP serwera g³ównego dla stref zapasowych,3,Brak
line3=Konfiguracja systemu,11
named_conf=Pe³na ¶cie¿ka do pliku named.conf,0
named_path=Pe³na ¶cie¿ka do programu named,0
whois_cmd=Pe³na ¶cie¿ka do polecenia whois,0
ndc_cmd=Pe³na ¶cie¿ka do komendy ndc,0
rndc_cmd=Pe³na ¶ciezka do komendy rndc,0
rndcconf_cmd=Pe³na ¶cie¿ka do komendy rndc-confgen,0
rndc_conf=Pe³na ¶ciezka do pliku rndc.conf,0
checkzone=Pe³na ¶cie¿ka do komendy named-checkzone,0
checkconf=Pe³na ¶cie¿ka do komendy named-chceckconf,0
keygen=Pe³na ¶cie¿ka do komendy dnssec-keygen,0
signzone=Pe³na ¶cie¿ka do komendy dnssec-signzone,0
pid_file=Domy¶lna lokalizacja pliku z&nbsp;numerem PID,3,/var/run/named.pid
no_pid_chroot=Plik PID jest w katalogu chroot?,1,0-Tak,1-Nie
start_cmd=Polecenie uruchamiaj±ce BINDa,3,Domy¶lne
stop_cmd=Komenda do zatrzymania BINDa,3,Zabij proces
restart_cmd=Komenda do zastosowania konfiguracji BINDa,10,-Wy¶lij sygna³ HUP, restart-Zatrzymaj i zrestartuj,Inna komenda
dnssectools_conf=Pe³na ¶cie¿ka do pliku dnssec-tools.conf,0
dnssectools_rollmgr_pidfile=Pe³na ¶cie¿ka do plików dnssec-tools rollmgr pid,0
dnssectools_rollrec=Pe³na ¶cie¿ka do plików dnssec-tools rollrec,0
dnssectools_keydir=Pe³na ¶cie¿ka do katalogów dnssec-tools key,0
