line2=Konfiguracja systemu,11
ftpd_path=Pe³na ¶cie¿ka do <tt>wuftpd</tt>,0
ftpaccess=Pe³na ¶cie¿ka do pliku <tt>ftpaccess</tt>,0
ftpconversions=Pe³na ¶cie¿ka do pliku <tt>ftpconversions</tt>,0
ftpgroups=Pe³na ¶cie¿ka do pliku <tt>ftpgroups</tt>,0
ftphosts=Pe³na ¶cie¿ka do pliku <tt>ftphosts</tt>,0
ftpusers=Pe³na ¶cie¿ka do pliku <tt>ftpusers</tt>,0
pid_file=Plik z&nbsp;numerem PID serwera FTP,0
log_file=Plik dziennika serwera FTP,0
