line1=Pilihan boleh konfigurasi,11
resolve=Penemuan alamat pelayan selesai,1,1-Ya,0-Tidak
scan_time=Masa menunggu untuk mengesan tindakbalas,0,5 
display_mode=Tunjuk palayan sebagai,1,1-Table,0-Ikon
sort_mode=Isih pelayan dengan,1,4-Alamat IP,1-Namahos,2-Keterangan,3-OS,5-Kumpulan,0-Urutan dicipta
show_status=Tunjuk status untuk pelayan,1,1-Ya,0-Tidak
line2=Konfigurasi sistem,11
groups_dir=Direktory kumpulan kelompok MSC,0
