line1=Opcje konfiguracyjne,11
resolve=Rozwiązywać znalezione adresy serwerów,1,1-Tak,0-Nie
scan_time=Czas oczekiwania na wynik skanowania,0
listen=Skanuj serwery na porcie UDP,3,Takim samym jak ten system
display_mode=Wyświetl serwery jako,1,1-Tabela,0-Ikony
sort_mode=Sortuj serwery według,4,4-Adresów IP,1-Nazwy hostów,2-Opisów,3-OS,5-Grup,0-Kolejności utworzenia
show_status=Wyświetl stan serwerów,1,1-Tak,0-Nie
show_ip=Zawsze wyświetlaj adres i port na stronie głównej,1,1-Tak,0-Nie
deflink=Domyślny tryb logowania,4,0-Normalne połączenie do serwera,1-Loguj przez Webmin,2-Loguj po kliknięciu na ikonę,3-Loguj z samym loginem i hasłem
deffast=Domyślny tryb RPC,1,1-Szybki,2-Automatyczny,0-Wolny
auto_type=Domyślny typ systemu,14,show_deftype
skipips=Adresy IP lub nazwy hostów systemu nie zostały wykryte,9,50,5,\t
skipifaces=Interfejs sieci nie został wykryty,0
max_servers=Pokaż formularz wyszukiwania&#44; jeśli liczba serwerów przekracza,0
