line1=Opcje konfiguracyjne,11
max_len=Maksymalna d³ugo¶æ polecenia do wy¶wietlenia,3,Nielimitowane
max_jobs=Maksymalna liczba zadañ Cron do wy¶wietlenia,3,Nielimitowane
show_time=Wy¶wietlaæ harmonogram pracy?,1,1-Tak,0-Nie
show_comment=Wy¶wietlaæ komentarze zadañ?,1,1-Tak,0-Nie
show_run=Wy¶wietlaæ stan uruchomionych zadañ?,1,2-Tak&#44; i pozwalaj na uruchamianie i zatrzymywanie,1-Tak,0-Nie
match_mode=Szukaj proces zadañ przez,1,1-tylko polecenie,0-Polecenie i argumenty
match_user=Dopasowaæ nazwy u¿ytkowników, przy szukaniu procesu zadania?,1,1-Tak,0-Nie
kill_subs=Zabiæ pod procesy, przy zabijaniu zadañ?,1,1-Tak,0-Nie
hourly_only=Pozwalaæ tylko na zadania maksymalnie godzinne?,1,0-Nie,1-Tak
add_file=Dodaj nowe zadania do pliku,3,Zwyk³y plik crontab u¿ytkownika
line2=Konfiguracja systemu,11
cron_dir=Katalog tablic crona,0
cron_get_command=Polecenie czytania zadañ u¿ytkownika dla crona,0
cron_edit_command=Polecenie modyfikacji zadañ u¿ytkownika dla crona,0
cron_copy_command=Polecenie przyjêcia zadania u¿ytkownika ze standardowego wej¶cia,0
cron_delete_command=Polecenie usuniêcia zadañ u¿ytkownika dla crona,0
cron_input=Cron pozwala na dodawanie zadañ,1,1-Tak,0-Nie
cron_allow_file=Plik z list± dopuszczonych u¿ytkowników,0
cron_deny_file=Plik z list± u¿ytkowników bez dostêpu,0
cron_deny_all=Uprawnienia przy braku plików pozwoleñ/zakazu,1,0-Zablokuj dla wszystkich,1-Zablokuj oprócz roota,2-Pozwól wszystkim
vixie_cron=Obsluga rozszerzeñ vixie-crona,1,1-Tak,0-Nie
system_crontab=Scie¿ka do systemowego pliku zadañ vixie-crona,0
single_file=¦cie¿ka do pliku crontab pojedynczego u¿ytkownika,0
cronfiles_dir=¦cie¿ka do katalogu z dodatkowymi plikami crona,3,Brak
run_parts=Polecenie run-parts,0
