squid_conf=Pe³na ¶cie¿ka do pliku konfiguracyjnego Squida,0
squid_start=Polecenie uruchamiaj±ce Squida,3,Automatycznie
squid_stop=Polecenie zatrzymuj±ce Squida,3,Automatycznie
squid_path=Program Squid,0
pid_file=Pe³na ¶cie¿ka do pliku z&nbsp;numerem PID Squida,0
cache_dir=Pe³na ¶cie¿ka do katalogu cache Squida,0
cachemgr_path=Program <tt>cachemgr.cgi</tt> Squida,0
log_dir=Pe³na ¶cie¿ka do katalogu logów Squida,0
calamaris=¦cie¿ka do programu analizy logów <tt>calamaris</tt>,3,Nie zainstalowano
cal_args=Argumenty dla polecenia <tt>calamaris</tt>,0
cal_max=Maksymalna liczba linii logu przekazywanych do <tt>calamaris</tt>,3,Nieograniczona
crypt_conf=Metoda szyfrowania hase³ dla proxy,1,0-crypt,1-md5base64
sort_conf=Uporz±dkowaæ u¿ytkowników proxy,1,1-Tak,0-Nie
