line1=Opcje konfigurowalne,11
display_max=Maksymalna liczba wy¶wietlanych u¿ytkowników lub grup,0
threshold_pc=Próg procentowy wykorzystanego limitu quota, od którego pod¶wietlaæ,3,Nie pokazuj
pc_show=Pokazuj procent wykorzystania limitu,1,2-Twardego i miêkkiego,1-Tylko twardego,0-Tylko miêkkiego
sort_mode=Sortuj u¿ytkowników i grupy wed³ug,1,0-Bloków u¿ytych,2-Nazwy,1-Kolejno¶ci z repquota,3-Twardego limitu bloków,4-Miêkkiego limitu bloków,5-Procentu u¿ycia z twardego limitu,6-Procentu u¿ycia z miêkkiego limitu
block_mode=Pokazuj quoty w ,1,1-Kilobajtach (je¶li mo¿liwe),0-Blokach
hide_uids=Pokazywaæ usuniêtych u¿ytkowników?,1,0-Tak,1-Nie
line1.1=Wiadomo¶ci e-mail w sprawie quota,11
email_msg=Wiadomo¶æ do u¿ytkowników przekraczaj±cych limit quoty,9,80,5,\t
email_subject=Temat wiadomo¶ci do u¿ytkowników,3,Domy¶lnie
gemail_msg=Wiadomo¶æ do grup przekraczaj±cych limity quoty,9,80,5,\t
gemail_subject=Temat wiadomo¶ci do grup,3,Domy¶lnie
line2=Konfiguracja systemu,11
show_grace=Pokazywaæ czasy ulgi je¶li dostêpne?,1,1-Tak,0-Nie
user_repquota_command=Polecenie wy¶wietlaj±ce u¿ytkowników w&nbsp;systemie plików,0
group_repquota_command=Polecenie wy¶wietlaj±ce grupy w&nbsp;systemie plików,0
user_edquota_command=Polecenie do zmiany quota u¿ytkownika,0
group_edquota_command=Polecenie do zmiany quota grupy,0
user_setquota_command=Polecenie do ustawienia quota u¿ytkownika,3,Brak
group_setquota_command=Polecenie do ustawienia quota grupy,3,Brak
user_quota_command=Polecenie do sprawdzenia quota u¿ytkownika,0
group_quota_command=Polecenie do sprawdzenia quota grupy,0
user_copy_command=Polecenie do skopiowania quota u¿ytkownika,0
group_copy_command=Polecenie do skopiowania quota grupy,0
user_quotaon_command=Polecenie do w³±czenia quota u¿ytkowników,0
group_quotaon_command=Polecenie do w³±czenia quota grup,0
user_quotaoff_command=Polecenie do wy³±czenia quota u¿ytkowników,0
group_quotaoff_command=Polecenie do wy³±czenia quota grup,0
quotacheck_command=Polecenie do naliczenia quota,0
user_grace_command=Polecenie do zmiany czasu ulgi dla u¿ytkowników,0
group_grace_command=Polecenie do zmiany czasu ulgi dla grup,0
