hide_dot_files=Wyświetlać pliki zaczynające się od kropki?,1,0-Tak,1-Nie
iconsize=Rozmiar przycisków na pasku narzędzi,1,1-Małe,0-Duże z etykietami
nocharset=Próbować użyć właściwego kodowania?,1,0-Tak,1-Nie
extract=Wypakować pliki .class z archiwów JAR?,1,1-Tak,0-Nie
width=Szerokość skalowania obrazków,3,Domyślnie (300 pikseli)
fixed=Rozmiar czcionki dla tekstu,3,Domyślnie (12 punktów)
small_fixed=Rozmiar czcionki dla przycisków,3,Domyślnie (10 punktów)
force_text=Edytor dla plików HTML,1,1-Edytor tekstowy,0-Edytor HTML
defzip=Domyślny tryb wysyłania archiwów,1,2-Wypakuj i usuń,1-Wypakuj,0-Nic nie rób 
defuser=Domyślny użytkownik do wysyłania,10,root-root,*-Taki sam jak katalog,Inny użytkownik
htmlexts=Rozszerzenia plików edytowanych jako HTML,3,Domyślnie (.htm and .html)
