hide_dot_files=Zobrazit i soubory začínající tečkou?,1,0-Ano,1-Ne
iconsize=Velikost tlačítek v panelu nástrojů,1,1-Malý,0-Velký s nadpisy
nocharset=Pokusit se používat správnou znakovou sadu?,1,0-Ano,1-Ne
extract=Rozbalit soubory .class pomocí JAR?,1,1-Ano,0-Ne
width=Šířka pro škálované obrázky,3,Výchozí (300 pixels)
fixed=Velikost fontu pro text,3,Výchozí (12 points)
small_fixed=Veliost fontu pro tlačítka,3,Výchozí (10 points)
force_text=Editor pro HTML soubory,1,1-Text editor,0-HTML editor
defzip=Výchozí mód archace pro nahrávání,1,2-Rozbalit a smazat,1-Rozbalit,0-Nic nedělat
defuser=Výchozí uživatel pro nahrávání,10,root-root,*-Stejný jako u adresáře,Jiný uživatel
