config_dir=Direktori konfigurasi Shorewall,0
shorewall=Lokasi kepada arahan shorewall,0
actions=Fail tindakan Standard,9,40,5,\t
macros=Direktori fail makro,0
before_apply_cmd=Arahan untuk dijalankan sebelum menerap konfigurasi,3,Tiada
after_apply_cmd=Arahan untuk dijalankan selepas menerapkan konfigurasi,3,Tiada
display_zone_descriptions=Memaparkan penerangan zon dalam fail peraturan?,1,0-Tidak,1-Ya
