sync_create=Vytvořit poštovní schránku při vytvoření uživatele?,1,1-Ano,0-Ne
line1=Systémová konfigurace,11
spam_report=Oznámit spam použitím,1,sa_learn-sa-learn --spam,spamassassin-spamassasin -r,-Rozhodnout automaticky
show_count=Zobrazit počet zpráv v Inboxu?,1,1-Ano,0-Ne
mailbox_user=Konfigurace adresáře v domovském adresáři pro Usermin,3,Nic
date_fmt=Formát data v seznamu mailů,1,dmy-DD/MM/YYYY,mdy-MM/DD/YYYY,ymd-YYYY/MM/DD
spam_del=Smazat spam při oznámení?,1,1-Ano,0-Ne
check_mod=Zkontrolovat změnu mailové schránky během mazání zprávy?,1,1-Ano,0-Ne
show_unread=Zobrazit počet nepřečtených zpráv?,1,2-Ano,0-Ne
smtp_user=Přihlašovací jméno pro SMTP mail server,3,Nic
mail_file=Soubor se zprávami v domovském adresáři uživatele,3,Nic
html_quote=Mód pro HTML kvótu,1,1-Zpráva pod <hr>,0-Zpráva uvnitř <blockquote>
wrap_width=Šířka pro zalomení poštovních zpráv,0,6
delete_warn=Ověřit si konfiguraci před mazáním?,10,y-Ano,n-Ne,Pro soubory složek větších než
smtp_auth=Metoda SMTP autentikace,4,-Výchozí,Cram-MD5-Cram-MD5,Digest-MD5-Digest-MD5,Plain-Plain,Login-Login
arrows=Zobrazit dolní šipky stránkovače pro,1,2-Složky i zprávy,1-Pouze složky,0-Nikdy
line3=Volby pro Spam,11
show_delall=Zobrazit tlačítko pro kompletní smazání poštovní schránky?,1,1-Ano,0-Ne
fwd_mode=Přeposlat zprávy s kvotací?,1,0-Ano,1-Ne
no_crlf=Přidat návrat řádku ( \r ) na konci každého řádku?,1,0-Ano,1-Ne
line2=Uživatelská konfigurace,11
top_buttons=Zobrazit tlačítka nahoře pro,1,2-Složky i zprávy,1-Pouze složky,0-Nikdy
sig_file=Soubor se signaturou,10,*-Nic,.signature-~/.signature,Jiný soubor
size_mode=Zahrnout všechny složky s nějakou velikostí?,1,1-Ano,0-Ne (pouze první složku)
mail_sub=Adresář pro zprávy v domovském adresáři uživatele,3,Nic
mail_style=Styl adresáře se soubory s poštou,4,0-mail/username,1-mail/u/username,2-mail/u/us/username,3-mail/u/s/username
auto=Automaticky detekovat umístění souborů s mailem?,1,1-Ano, založeno na poštovním serveru,0-Ne, použít níže uvedené nastavení ..
sync_modify=Přejmenovat poštovní schránku při přejmenování uživatele?,1,1-Ano,0-Ne
ignore_users_enabled=        Stav seznamu pro ignorování,1,1-Zapnutý,0-Vypnutý
sync_perms=Práva pro nové poštovní schránky,0,4
date_tz=Časová zóna při zobrazení data,3,Výchozí systémové
show_to=Zobrazit Komu: adresu v poštovních schránkách?,1,1-Ano,0-Ne
sort_mode=Třídit poštovní schránky podle,1,2-Velikosti,1-Jména,0-souboru s hesly (passwd)
spam_buttons=Zobrazit tlačítka pro oznámení spamu pro,2,seznam-Poštovní schránky,mail-Zprávy
from_dom=Doména užívaná v Od: adrese,3,Hostname systému
line4=Volby VPOPMail,11
html_edit=Používat při psaní zprávy HTML editor?,1,2-Vždy,1-Při odpovědi na HTML mail,0-Nikdy
mail_dir=Adresář pro uživatelské soubory s poštou,3,Nic
download=MIME typy příloh, které budou vždy nahrány,9,20,4,\t
ldap_pass=Heslo do LDAP serveru,0
vpopmail_dir=Hlavní adresář pro VPOPMail,0
from_virtualmin=Získat Od: adresu z Virtualminu?,1,1-Ano,0-Ne
ldap_port=Port LDAP serveru,3,Výchozí
perpage=Počet zobrazených zpráv na jedné stránce,0,6
show_mail=Zobrazit pouze uživatele s mailem?,1,1-Ano,0-Ne
show_sent=Zobrazit počet zpráv ve složce s odeslanou poštou?,1,1-Ano,0-Ne
ldap_host=LDAP server,0
mail_usermin=Styl (pod)složek v domovském adresáři zobrazený v Userminu,3,Nic
line5=Volby pro Qmail+LDAP,11
sync_delete=Smazat poštovní schránku při smazaní uživatele?,1,1-Ano,0-Ne
log_read=Nahrát čtení zprávy do Logu Webmin akcí?,1,1-Ano,0-Ne
from_addr=Od: adresa užívaná pro ruční odeslání zprávy,3,Jméno uživatele poštovní schránky
ldap_login=Přihlášení do LDAP serveru,0
mail_system=Nainstalovaný poštovní server,4,1-Sendmail,0-Postfix,2-Qmail,4-Qmail+LDAP,5-Qmail+VPopMail,3-Zjistit automaticky
track_read=Označovat přečtenou/nepřečtenou poštu,1,1-Ano,0-Ne
open_mode=Otevřít zprávy v,1,1-Novém okně,0-Tom samém okně
show_size=Mód zobrazení uživatelů,1,0-Pouze jména uživatelů,1-Jména uživatelů a velikost,2-Všechny detaily
ldap_base=Zdroj pro poštovní uživatele,0
line0=Konfigurovatelné volby,11
link_mode=Otevírat odkazy v,1,1-Novém okně,0-Tom samém okně
show_body=Zobrazit v rámci seznamu náhled těla zprávy?,1,1-Ano,0-Ne
line3.5=Volby pro Od: adresu,11
view_html=Zobrazit tělo zprávy jako,4,0-Vždy jako běžný text,1-Je-li to možné jako text, jinak HTML,2-Je-li to možné jako HTML, jinak jako text,3-Konvertovat HTML do běžného textu
max_records=Maximální počet zobrazených uživatelů,0,6
show_size_below=       Jména uživatelů a velikost - Kde bude zobrazena velikost,1,0-napravo od jména,1-pod jménem
webmin_from=Použitá Od: adresa v momentě, kdy odesílá mail Webmin,3,Výchozí (webmin@<i>vášhost</i>)
column_count=Počet sloupců se zobrazenými uživatelskými jmény,1,3-3,4-4,5-5,6-6,7-7,8-8,9-9
smtp_pass=Heslo pro SMTP mail server,3,Nic
ignore_users=Ignorovat tyto uživatele (nezobrazovat),15,userIgnoreList
bcc_to=Skrytá kopie: odeslat zprávy adresátu,0
send_mode=Odeslat zprávu pomocí,10,-Programu v poštovním serveru,SMTP serveru
