passwd_file=Plik hase³,3,Wygenerowany
group_file=Plik grup,0
shadow_file=Plik hase³ "shadow",3
master_file=Nadrzêdny plik hase³ BSD,3
gshadow_file=Plik grup "shadow",3
pre_command=Polecenie uruchamiane przed dokonaniem zmian,0
post_command=Polecenie uruchamiane po dokonaniu zmian,0
homedir_perms=Prawa dostêpu do nowych katalogów domowych,0
base_uid=Najni¿szy UID dla nowych u¿ytkowników,0,5
base_gid=Najni¿szy GID dla nowych grup,0,5
default_group=Domy¶lna grupa dla nowych u¿ytkowników,6,Domy¶lne
default_shell=Domy¶lna pow³oka dla nowych u¿ytkowników,3,Pierwsza na li¶cie
display_max=Maksymalna liczba wy¶wietlanych u¿ytkowników,0
sort_mode=Wy¶wietlaj u¿ytkowników i&nbsp;grupy wg,1,0-Porz±dku w zbiorze,1-Nazwy u¿ytkownika,2-Rzeczywistej nazwy,3-Nazwiska,4-Pow³oki,5-Nru UID lub GID,6-Katalogu domowego
last_count=Wy¶wietlana liczba poprzednich logowañ,3,Nieograniczona
new_user_group=Tworzyæ now± grupê dla nowych u¿ytkowników,1,1-Tak,0-Nie
skip_md5=Nie uzywaj kodowania hase³ MD5, je¿eli modu³ perla MD5 nie jest zainstalowag,1,1-Tak,0-Nie
user_files=Kopiowaæ pliki do nowego katalogu domowego z,9,40,3
display_mode=Wy¶wietlanie u¿ytkowników i&nbsp;grup wg,1,2-Grupy podstawowej,1-Pe³nej informacji,0-Tylko nazwy
passwd_stars=Ukrywaæ tre¶æ has³a?,1,1-Tak,0-Nie
delete_only=Kasowaæ tylko pliki bêd±ce w³asno¶ci± u¿ytkownika?,1,1-Tak,0-Nie
from_files=Pobieraæ grupy podstawowe z,1,1-Plików,0-Odwo³añ do systemu
alias_check=Sprawdzaæ kolizje z&nbsp;aliasami Sendmaila,1,1-Tak,0-Nie
home_base=Lokalizacja automatycznie tworzonych katalogów domowych,3,Nie ustawona
home_style=Postaæ automatycznie tworzonych katalogów domowych,4,0-home/u¿ytkownik,1-home/u/u¿ytkownik,2-home/u/u¿/u¿ytkownik,3-home/u/¿/u¿ytkownik
random_password=Generowaæ has³a dla nowych u¿ytkowników?,1,1-Tak,0-Nie
extra_real=Pokazywaæ dane o pracy i&nbsp;telefonach?,1,1-Tak,0-Nie
