line1=Opcje katalogu domowego,11
homedir_perms=Prawa dostępu do nowych katalogów domowych,0
user_files=Kopiować pliki do nowego katalogu domowego z,9,40,3
home_base=Lokalizacja automatycznie tworzonych katalogów domowych,3,Nie ustawona
home_style=Postać automatycznie tworzonych katalogów domowych,4,0-home/użytkownik,1-home/u/użytkownik,2-home/u/uż/użytkownik,3-home/u/ż/użytkownik
line2=Opcje nowego użytkownika,11
base_uid=Najniższy UID dla nowych użytkowników,0,5
base_gid=Najniższy GID dla nowych grup,0,5
new_user_group=Tworzyć nową grupę dla nowych użytkowników,1,1-Tak,0-Nie
alias_check=Sprawdzać kolizje z&nbsp;aliasami Sendmaila,1,1-Tak,0-Nie
delete_only=Kasować tylko pliki będące własnością użytkownika?,1,1-Tak,0-Nie
line3=Domyślne nowego użytkownika,11
default_group=Domyślna grupa dla nowych użytkowników,6,Domyślne
default_secs=Domyślne drugorzędne grupy dla nowych użytkowników,3,Brak
default_shell=Domyślna powłoka dla nowych użytkowników,3,Pierwsza na liście
default_min=Domyślna liczba minimalna dni dla nowych użytkowników,3,Brak
default_max=Domyślna liczba maksymalna dni dla nowych użytkowników,3,Brak
default_warn=Domyślna liczba dni do ostrzeżenia dla nowych użytkowników,3,Brak
default_inactive=Domyślna liczba nieaktywnych dni dla nowych użytkowników,3,Brak
default_expire=Domyśla data ważności dla nowych użytkowników (dd/mm/yyyy),3,Brak
default_other=Tworzenie i aktualizacja w innych modułach,1,1-Tak,0-Nie
line4=Opcje wyświetlania,11
display_max=Maksymalna liczba wyświetlanych użytkowników,0
sort_mode=Wyświetlaj użytkowników i&nbsp;grupy wg,1,0-Porządku w zbiorze,1-Nazwy użytkownika,2-Rzeczywistej nazwy,3-Nazwiska,4-Powłoki,5-Nru UID lub GID,6-Katalogu domowego
last_count=Wyświetlana liczba poprzednich logowań,3,Nieograniczona
last_show=Wyświetlać ostatnie logowanie na liście użytkowników?,1,1-Tak,0-Nie
display_mode=Wyświetlanie użytkowników i&nbsp;grup wg,1,2-Grupy podstawowej,1-Pełnej informacji,0-Tylko nazwy
passwd_stars=Ukrywać treść hasła?,1,1-Tak,0-Nie
from_files=Pobierać grupy podstawowe z,1,1-Plików,0-Odwołań do systemu
random_password=Generować hasła dla nowych użytkowników?,1,1-Tak,0-Nie
extra_real=Pokazywać dane o pracy i&nbsp;telefonach?,1,1-Tak,0-Nie
delete_root=Pozwalać na usuwanie systemowych użytkowników i grup?,1,1-Tak,0-Nie
line5=Ograniczenia hasła,11
passwd_min=Minimalna długość hasła,3,Brak minimum
passwd_dict=Zabraniać używania haseł słownikowych?,1,1-Tak,0-Nie
dict_file=Pliki zawierające słowa słownika,3,Domyślne systemowe
line0=Polecenia przed i po,11
pre_command=Polecenie uruchamiane przed dokonaniem zmian,0
post_command=Polecenie uruchamiane po dokonaniu zmian,0
line6=Konfiguracja systemu,11
passwd_file=Plik haseł,3,Wygenerowany
group_file=Plik grup,0
shadow_file=Plik haseł "shadow",3
master_file=Nadrzędny plik haseł BSD,3
gshadow_file=Plik grup "shadow",3
lock_string=Hasło zastępujące hasła do zablokowanych kont,0
nscd_restart=Polecenie restartu nscd,3,Wyślij sygnał HUP
