dhcpd_conf=Plik konfiguracyjny serwera DHCP,0
dhcpd_path=Plik programu serwera DHCP,0
interfaces=Interfejsy&#44; na których ma pracowaæ DHCP,3,Automatycznie
pid_file=¦cie¿ka do pliku z&nbsp;numerem PID serwera DHCP,0
lease_file=Plik dzier¿aw serwera DHCP,0
lease_sort=Uporz±dkuj dzier¿awy wg,1,0-Kolejno¶ci w&nbsp;pliku,1-Adresów IP,2-Nazw hostów
hostnet_list=Poka¿ podsieci i&nbsp;hosty jako,1,0-Ikony,1-Listê
dhcpd_nocols=Ilo¶æ ikon w&nbsp;wierszu,0
lease_tz=Pokazuj czas dzier¿awy wg,1,0-GMT,1-Czasu lokalnego
