dhcpd_conf=Archivo de configuración del servidor DHCP,0
dhcpd_path=Ejecutable del servidor DHCP,0
interfaces=Interfaces donde ejecutar DHCP,3,Automática
pid_file=Trayectoria a archivo PID del servidor DHCP,0
lease_file=Archivo de arriendo del servidor DHCP,0
lease_sort=Clasificar arriendos por,1,0-Orden en archivo,1-Direcciones IP,2-Nombre de máquina
hostnet_list=Mostrar subredes y máquinas como,1,0-Iconos,1-Lista
dhcpd_nocols=Iconos en fila,0
lease_tz=Mostrar tiempos de arriendo en,1,0-GMT,1-Hora local
list_listen_interfaces=Lista de Interfaces Listen,1,0-Solo los Interfaces Activos,1-Todos los Interfaces
