#!/bin/sh
source /etc/sysconfig/printers/XXX
if [ "$PAPERSIZE" = "a4" ]; then
  T=A4
else
  T=Letter
fi

enscript -M $T -Z -p - |

if [ "$DOUBLEPAGE" = "true" ]; then
  psnup -d -b0.6cm -p$PAPERSIZE -2
else
  cat -
fi |

if [ "$GSDEVICE" = "PostScript" ]; then
	cat -
elif [ "$GSDEVICE" = "uniprint" ]; then
	exec 3>&1 1>&2
	gs @$UPP.upp -q -sOutputFile="|cat 1>&3"
else
	gs -q $GSOPTIONS -sDEVICE=$GSDEVICE \
		-r$RESOLUTION \
		-sPAPERSIZE=$PAPERSIZE \
		-dNOPAUSE \
		-dSAFER \
		-sOutputFile=- -
fi

if [ "$SENDEOF" != "" ]; then
	printf "\004"
fi

exit 0
