stop_cmd=Příkaz ukončující plánovač,3,Determinován stylem tiskárny
sort_mode=Seřadit tiskárny podle,1,1-jména,0-pořadí v systému
line2=Konfigurace systému,11
gs_path=Cesta k ghostscript,3,Nic
start_cmd=Příkaz spouštějící plánovač,3,Determinován stylem tiskárny
line1=Možnosti konfigurace,11
show_status=Zobrazit použitelné a akceptovatelné stavy místo driveru?,1,1-ano,0-ne
apply_cmd=Příkaz spuštěný po jakékoliv změně,3,Nic
printcap_file=Soubor tiskáren,3,Nic
hpnp_path=Cesta k programu hpnp,3,Nic
model_path=Adresář obsahující programy rozhraní,3,Nic
gs_fontpath=Adresáře pro Ghostscript fonty,3,Výchozí
queue_refresh=Počet vteřin před obnovou tiskové fronty,3,Neobnovovat
show_jobs=Zobrazit na hlavní stránce počet úloh ve frontách?,1,1-ano,0-ne
display_mode=Na hlavní stránce zobrazit,1,1-jenom jména tiskáren,0-Úplné detaily
print_style=Styl konfigurace tiskáren,4,solaris-Solaris,linux-Linux,freebsd-FreeBSD,hpux-HPUX,lprng-LPRng,unixware-UnixWare,cups-CUPS,irix-IRIX
driver_style=Styl driverů diskáren,4,webmin-Webmin,caldera-Caldera,redhat-Redhat,hpux-HPUX,suse-SuSE,cups-CUPS,irix-IRIX,printconf-Redhat Printconf
smbclient_path=Cesta k smbclient,3,Nic
gs_lib=Adresáře Ghostscript knihoven,3,Výchozí
