index_status=Stan pokazywany na li¶cie,1,1-Stan bie¿±cy,0-Z&nbsp;ostatniego regularnrgo sprawdzenia
pager_cmd=Polecenie do wys³ania wiadomo¶ci na pager,3,Brak
refresh=Sekundy pomiêdzy od¶wie¿eniami strony,3,Nie od¶wie¿aj
sort_mode=Sortuj monitory wed³ug,1,0-Kolejno¶ci tworzenia,1-Opisu,2-Hosta,3-Ostatniego stanu
columns=Kolumny dla tabeli us³ug,1,2-2,1-1
output=Przej±æ komunikaty wyj¶ciowe z uruchomionych programów&#44; gdy przestan± dziaæ?,1,1-Tak,0-Nie
subject_mode=Tryb tematu e-mail,1,0-Nowy styl,1-Stary styl
def_tmpl=Domy¶lny szablon,10,-Brak,Szablon o nazwie
pinger=Wy¶lij pingi przez polecenie,10,-U¿yj wbudowany kod,linux-U¿yj polecenia Linux lub FreeBSD,Inne polecenie
snmp_server=Wy¶lij sygna³y SNMP trap do serwera,3,Brak
snmp_version=Protokó³ wersji SNMP,1,3-v3,2-v2,1-v1
snmp_community=Community string SNMP,0
snmp_trap=SNMP OID dla sygna³ów trap,0
history_show=Liczba historycznych stanów do wy¶wietlenia,0
history_purge=Liczba dni przechowywania historycznych stanów,0
