line1=Configureerbare opties,11
lease=Acceptabel aantal seconden vertraging tussen systeem tijd en hardware tijd,0
timeserver=Standaard tijd server,3,Geen
ntp_only=Gebruik alleen NTP voor tijd synchronisatie?,1,1-Ja,0-Nee
line2=Systeem configuratie,11
hwtime=Systeem ondersteund hardware tijd?,1,1-Ja,0-Nee,2-Detecteer automatisch
seconds=Systeem tijd formaat,1,1-MMDDUUMMJJJJ.SS,0-MMDDUUMMJJ,2-JJJJMMDDUUMM.SS
zone_style=Tijdzone configuratie methoden,4,linux-Linux,freebsd-FreeBSD,solaris-Solaris,-&lt;Niet ondersteund op dit OS&gt;
hwclock_flags=Opdracht regel flags voor hwclock,10,-Geen,sysconfig-Van /etc/sysconfig/clock
