line1=Nastaviteµné voµby,11
lease=Akceptovateµný poèet sekúnd rozdielu medzi systémovým èasom a hardvérovým èasom,0
timeserver=©tandardný èasový server,3,®iadny
ntp_only=Pou¾íva» len NTP pre synchronizáciu èasu?,1,1-Áno,0-Nie
line2=Systémová konfigurácia,11
seconds=Formát systémového èasu ,1,1-MMDDHHMMRRRR.SS,0-MMDDHHMMRR,2-RRRRMMDDHHMM.SS
zone_style=Metóda konfigurácie èasovej zóny,4,linux-Linux,freebsd-FreeBSD,solaris-Solaris,-&lt;Nepodporované na tomto OS&gt;
hwclock_flags=Parametre pre hwclock,10,®iadne,sysconfig-z /etc/sysconfig/clock
