line1=Configureerbare opties,11
display_mode=Hoofdpagina toont,1,0-Alle opdrachten en parameters,1-Links naar opdrachten
width=Breedte van bestand bewerkings venster,3,Standaard (80 karakters)
height=Hoogte van file bewerkings venster,3,Standaard (20 karakters)
wrap=File bewerker terugloop modus,1,-Standaard (Zacht),hard-Hard,off-Uit
columns=Kolommen om opdrachten in te tonen,1,2-2,1-1
sort=Sorteer opdrachten met,1,desc-Opdracht naam,html-Omschrijving,-Opdracht volgorde
params_file=Behandel standaard waardes die eindigen met / als een te lezen file?,1,1-Ja,0-Nee
params_cmd=Behandel standaard waardes die eindigen met | als uit te voeren opdracht?,1,1-Ja,0-Nee
