start_cmd=Příkaz ke startu mysql serveru,0
max_dbs=Maximální počet zobrazených databází a tabulek,0,5
style=Ukázat databáze a tabulky jako,1,1-seznam,0-Ikony
mysql_data=Cesta k adresáři s MySQL databázemi,3,Nic
date_subs=Uplatnit <tt>strftime</tt> substituce v cíli zálohování?,1,1-Ano,0-Ne
pass=Heslo administrátora MySQL,0
passwd_mode=Mod pro transformaci hesla,1,1-Starý,0-Výchozí
add_mode=Použít rozhraní s editací řádku vertikálně?,1,1-ano,0-ne
line1=Možnosti konfigurace,11
login=Jméno administrátora MySQL,0
port=MySQL port pro připojení k,3,Výchozí
mysqladmin=Cesta k příkazu mysqladmin,0
mysql_libs=Cesta k adresáři sdílených knihoven,3,Nic
sock=MySQL socket soubor,3,Výchozí
nodbi=Použít DBI připojení (je-li k dispozici)?,1,0-ano,1-ne
mysqlimport=Cesta k příkazu mysqlimport,0
mysql=Cesta k příkazu mysql,0
stop_cmd=Příkaz k zastavení mysql serveru,3,Automaticky
charset=Znaková sada pro MySQL data,15,charset
line2=Konfigurace systému,11
my_cnf=Konfigurační soubor MySQL,0
perpage=Počet řádků zobrazených na stránce,0
mysqlshow=Cesta k příkazu mysqlshow,0
max_text=Maximální zobrazovaná délka pro textová pole,3,Neomazeno
blob_mode=Zobrazit pole blob a text jako,1,0-Data v tabulce,1-Odkazy ke stažení
encoding=Kódování pro obsah databáze,3,Výchozí (z daného jazyka)
host=MySQL host pro připojení k,3,localhost
mysqldump=Cesta k příkazu mysqldump,0
mysqld=Cesta k příkazu mysqld,3,Automaticky
