line1=Opcje konfiguracyjne,11
lines=Domy¶lna liczba wy¶wietlanych linii,0
refresh=Sekundy pomiêdzy od¶wie¿eniami loga,3,Nigdy
compressed=Do³±czaæ skompresowane logi do wyszukiwarki?,1,1-Tak,0-Nie
others=Wy¶wietliæ logi z innych modu³ów?,1,1-Tak,0-Nie
extras=Inne pliki logów do wy¶wietlenia<br>(Z opcjonalnymi opisami),9,50,4,\t
line2=Konfiguracja systemu,11
syslog_conf=¦cie¿ka do pliku konfiguracyjnego sysloga,0
m4_conf=Czy konfiguracja sysloga tworzona poprzez m4?,1,1-Tak,0-Nie
m4_path=¦cie¿ka do m4,0
sync=Mo¿na wy³±czyæ synchronizacjê po ka¿dym komunikacie?,1,1-Tak,0-Nie
pipe=Mo¿e logowaæ do nazwanych potoków?,1,2-Do poleceñ,1-Do nazwanych potoków,0-Nie
socket=Obs³uga logowania do socketów?,1,1-Tak,0-Nie
pri_dir=Obs³uga zaawansowanego wyboru priorytetów?,1,2-Styl FreeBSD,1-Styl Linuksa,0-Nie
pri_all=Obs³uguje wszystkie priorytety?,1,1-Tak,0-Nie
tags=Obs³uga oznaczonych sekcji?,1,1-Tak,0-Nie
pid_file=Plik(i) z numerem PID sysloga,3,Brak
syslogd=¦cie¿ka do programu serwera syslog,0
facilities=Obs³ugiwane pochodzenie zdarzenia,0
start_cmd=Polecenie do uruchomienia syslog,3,Tylko uruchom serwer
restart_cmd=Polecenie do zastosowania zmian,3,Zatrzymaj i ponownie uruchom serwer
signal_cmd=Polecenie do ponownego otwarcia plików logów,3,Wy¶lij sygna³ HUP
tail_cmd=Polecenie Taiil i opcje,3,Domy¶lnie (tail -n LINES)
