line1=Opcje konfigurowalne,11
show_list=Wy¶wietlanie serwerów wirtualnych jako,1,0-Ikony,1-Listê
show_order=Kolejno¶æ serwerów wirtualnych wg,1,0-Porz±dku w&nbsp;plikach konfiguracyjnych,1-Nazwy servera,2-Adresu IP
max_servers=Maksymalna liczba wy¶wietlanych serwerów,0,5
virt_file=Serwery wirtualne dodawane w&nbsp;pliku,3,httpd.conf
virt_name=Wzór nazwy pliku dla serwerów wirtualnych,3,Domy¶lny ($DOM.conf)
link_dir=Katalog do tworzenia ³±czy dla nowych serwerów wirtualnych,3,Brak
test_config=Sprawdzaæ plik konfiguracyjny przed zastosowaniem zmian?,1,1-Tak,0-Nie
test_manual=Testowaæ plik konfiguracyjny po rêcznych zmianach?,1,1-Tak,0-Nie
test_always=Testowaæ plik konfiguracji po innych zmianach?,1,1-Tak,0-Nie
test_apachectl=Testuj konfiguracjê z komendami,1,1-<tt>apachectl configtest</tt>,0-<tt>httpd</tt> z opcj± <tt>-D</tt>
show_names=Wy¶wietlaæ nazwy dyrektyw Apache?,1,1-Tak,0-Nie
apache_docbase=Katalog bazowy dla dokumentacji Apache,3,witryna Apache
auto_mods=Wykrywaæ automatycznie modu³y Apache?,1,1-Tak,0-Nie
allow_virtualmin=Zezwalaæ na edycjê domen zarz±dzanych przez Virtualmin?,1,1-Tak,0-Nie
line2=Konfiguracja systemu,11
httpd_dir=Katalog g³ówny serwera Apache,0
httpd_path=¦cie¿ka do pliku programu httpd,0
httpd_version=Wersja Apache,3,Automatycznie
apachectl_path=¦cie¿ka do polecenia apachectl,3,Brak
start_cmd=Polecenie uruchamiaj±ce apache'a,3,Automatycznie
stop_cmd=Polecenie zatrzymuj±ce apache'a,3,Automatycznie
apply_cmd=Komenda do zastosowania konfiguracji,10,-U¿yj apachectl lub signal HUP,Restart-Uruchom komendy stop i strat
graceful_cmd=Komenda do ponownego odczytu konfiguracji,3,Taka sama jak komenda zastosowania
httpd_conf=¦cie¿ka do httpd.conf,3,Automatycznie
srm_conf=¦cie¿ka do srm.conf,3,Automatycznie
access_conf=¦cie¿ka do access.conf,3,Automatycznie
mime_types=¦cie¿ka do mime.types,3,Automatycznie
pid_file=¦cie¿ka do pliku PID Apache,3,Automatycznie
line3=Zmienne Apache,11
defines_file=Plik ¶rodowiska definiuj±cy zmienne Apache,3,Brak
defines_name=Nazwa zmiennej ¶rodowiskowej w powy¿szym pliku,0
defines_mods=Katalogi zawieraj±ce modu³y dla zmiennych HAVE_,9,40,3,\t
