htaccess=Apache opties file naam,0
htpasswd=Gebruikers file naam,0
htgroups=Groepen file naam,0
sort=Sorteer gebruikers met,1,1-Gebruikersnaam,0-Volgorde in file
md5=Mogelijkheid tot MD5 encryptie optie?,1,1-Ja,0-Nee
sha1=Mogelijkheid tot SHA1 encryptie optie?,1,1-Ja,0-Nee
digest=Diverse encryptie opties geven?,1,1-Ja,0-Nee
extra_directives=Extra richtlijnen invoegen in .htaccess,9,0,0,\t
perms=Permissies voor aanmaken van files,3,Standaard (644)
