line1=Configureerbare opties,11
refresh_days=Aantal dagen tussen verversing van de CPAN module lijst,0,5
save_partial=Gedownloade modules bewaren als de installatie mislukt?,1,1-Ja,0-Nee
def_args=Standaard opties voor Makefile.PL,0
incpackages=Softwarepakketten van Perl modules opnemen?,1,1-Ja,0-Nee
incyum=Installeer Perl modules van YUM of APT wanneer beschikbaar?,1,1-Ja,0-Nee
line2=Systeem configuratie,11
packages=CPAN perl modules lijst,0
cpan=CPAN modules basis URL,0
