name: Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  prove:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Perl::Critic
        run: sudo apt-get update && sudo apt-get install -y libperl-critic-perl
      - name: prove -lr
        run: prove -lr
